[versions]
java = "17"
junit = "5.8.2"
indra = "2.1.1"
toxopid = "1.3.1"
nullaway = "0.9.5"
versions = "0.42.0"
jetbrains-annotations = "23.0.0"
errorprone-gradle = "2.0.2"
errorprone-core = "2.11.0"

[libraries]
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone-core" }

[plugins]
toxopid = { id = "fr.xpdustry.toxopid", version.ref = "toxopid" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-gradle" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-publishing = { id = "net.kyori.indra.publishing", version.ref = "indra" }
