[versions]
shadow = "8.3.2"
indra = "3.1.3"
toxopid = "4.1.0"

[plugins]
indra-common = { id = "net.kyori.indra", version.ref = "indra" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
toxopid = { id = "com.xpdustry.toxopid", version.ref = "toxopid" }
