[versions]
java = "17"
junit = "5.8.2"
indra = "2.1.1"
toxopid = "1.3.0"
nullaway = "0.9.4"
jetbrains-annotations = "23.0.0"
errorprone-gradle = "2.0.2"
errorprone-core = "2.10.0"
errorprone-javac = "9+181-r4173-1"

[libraries]
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
nullaway = { module = "com.uber.nullaway:nullaway", version.ref = "nullaway" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone-core" }
errorprone-javac = { module = "com.google.errorprone:javac", version.ref = "errorprone-javac" }

[plugins]
toxopid = { id = "fr.xpdustry.toxopid", version.ref = "toxopid" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-gradle" }
indra-git = { id = "net.kyori.indra.git", version.ref = "indra" }
indra-publishing = { id = "net.kyori.indra.publishing", version.ref = "indra" }
