name: AutoRelease

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build plugin jar
        run: ./gradlew jar
      - name: Get the version
        run: echo "tag=$( cat plugin.json | grep "version*" | cut -d : -f 2,3 | tr -d \", )" >> $GITHUB_ENV
      - 
