name: AutoRelease

on:
  push:
    tags:
      - '*'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build plugin jar
        run: ./gradlew jar

      - name: Get the release number
        id: release_tag
        run: |
          tag=$(cat plugin.json)                         # Set the release tag# Read plugin.json
          tag=$(echo $tag | grep "version*")             # Cut the line with the version
          tag=$(echo $tag | cut -d ":" -f 2,3)           # Split with ":" and take the version number
          tag=$(echo $tag | tr -d \"," ")                # Trim the " and , and spaces
          echo "::set-output name=RELEASE_TAG::$tag"     # Set the environment variable

      - name: Upload artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/*.jar
          tag: ${{ steps.read_release.outputs.RELEASE_TAG }} # <--- Use environment variables that was created earlier
